name : unit-tests

on :
    push : 
        branches: 'master'
    
    pull_request: 
        types: [opened, synchronize, closed]
    
jobs : 
    build :
        runs-on: ubuntu-latest
        steps : 
            - name : Checks out the project on runner
              uses : actions/checkout@v4

            - name : Set up JDK 21
              uses : actions/setup-java@v4
              with : 
                java-version : '21'
                distribution: 'oracle'
            - name : Run unit tests
              shell : powershell
              run : |
                mvn -v
                mvn clean test      



